### ISSUE TITLE
email confirmation bug 

### ISSUE THREAD

**Issue by CARDRAMZ** [dappforce/subsocial-web-app#421]
When the confirmation email arrives, the confirmation icon does not have the confirmation link

**Comment by siman** [comment]
Please try to request email again. It should be fixed now.

**Comment by siman** [comment]
I believe that we fixed this issue. @CARDRAMZ if there is still a problem with this, please feel free to comment here.

**Comment by CARDRAMZ** [comment]
now work perfectly thanks a lot

**Comment by CARDRAMZ** [comment]
> I believe that we fixed this issue. @CARDRAMZ if there is still a problem with this, please feel free to comment here.

now work perfectly thanks a lot
